"""Convert the trained Keras model to int8 TFLite and emit a C array.

Steps
-----
1. Load ``artifacts/models/hey_jarvis.keras``.
2. Build a representative-data generator from real MFCC features so the
   quantizer can calibrate activations.
3. Run ``TFLiteConverter`` with full integer post-training quantization
   (int8 weights, int8 activations, int8 input/output).
4. Save the .tflite file and a C++ source containing the byte array.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import tensorflow as tf
from tqdm import tqdm

from audio_utils import fix_length, iter_wav_files, load_wav
from config import (
    C_ARRAY_PATH,
    FEATURE_SHAPE,
    KERAS_PATH,
    NEGATIVE_DIR,
    POSITIVE_DIR,
    TFLITE_PATH,
    TRAIN,
    ensure_dirs,
)
from features import compute_mfcc


def _representative_dataset(num_samples: int = 200):
    """Yield real MFCC features for quantizer calibration."""
    rng = np.random.default_rng(TRAIN.random_seed)
    pos_files = list(iter_wav_files(POSITIVE_DIR))
    neg_files = list(iter_wav_files(NEGATIVE_DIR))
    pool = pos_files + neg_files
    if not pool:
        # Fallback to random noise if the user hasn't prepared the dataset.
        def _gen():
            for _ in range(num_samples):
                noise = rng.standard_normal(FEATURE_SHAPE).astype(np.float32) * 0.1
                yield [noise[np.newaxis, ...]]
        return _gen
    rng.shuffle(pool)
    pool = pool[:num_samples]

    def _gen():
        for f in tqdm(pool, desc="calibration", leave=False):
            try:
                audio = fix_length(load_wav(f))
                feats = compute_mfcc(audio).astype(np.float32)
                yield [feats[np.newaxis, ...]]
            except Exception:
                continue
    return _gen


def convert_to_tflite(keras_path: Path = KERAS_PATH,
                      tflite_path: Path = TFLITE_PATH) -> Path:
    ensure_dirs()
    model = tf.keras.models.load_model(keras_path)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = _representative_dataset()
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_bytes = converter.convert()
    tflite_path.parent.mkdir(parents=True, exist_ok=True)
    tflite_path.write_bytes(tflite_bytes)
    print(f"[ok] wrote {tflite_path} ({len(tflite_bytes)/1024:.1f} kB)")
    return tflite_path


def emit_c_array(tflite_path: Path = TFLITE_PATH,
                 cpp_path: Path = C_ARRAY_PATH,
                 var_name: str = "g_model") -> Path:
    data = tflite_path.read_bytes()
    cpp_path.parent.mkdir(parents=True, exist_ok=True)
    header = cpp_path.with_suffix(".h")

    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    array_body = "\n".join(lines).rstrip(",")

    stamp = datetime.utcnow().isoformat() + "Z"
    cpp_content = f"""// Auto-generated by python/convert.py on {stamp}
// Do not edit — regenerate via `python convert.py`.
#include "model.h"

alignas(16) const unsigned char {var_name}[] = {{
{array_body}
}};

const unsigned int {var_name}_len = {len(data)};
"""
    header_content = f"""// Auto-generated header for {var_name}.
#pragma once

#ifdef __cplusplus
extern "C" {{
#endif

extern const unsigned char {var_name}[];
extern const unsigned int {var_name}_len;

#ifdef __cplusplus
}}
#endif
"""
    cpp_path.write_text(cpp_content)
    header.write_text(header_content)
    print(f"[ok] wrote {cpp_path} ({len(data)} bytes embedded)")
    print(f"[ok] wrote {header}")
    return cpp_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--keras", type=str, default=str(KERAS_PATH))
    parser.add_argument("--tflite", type=str, default=str(TFLITE_PATH))
    parser.add_argument("--cpp", type=str, default=str(C_ARRAY_PATH))
    parser.add_argument("--skip-c-array", action="store_true",
                        help="Only produce the .tflite file.")
    args = parser.parse_args()

    keras = Path(args.keras)
    if not keras.exists():
        print(f"[error] {keras} does not exist. Run train.py first.", file=sys.stderr)
        return 1

    convert_to_tflite(keras, Path(args.tflite))
    if not args.skip_c_array:
        emit_c_array(Path(args.tflite), Path(args.cpp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
